# Generated by Django 4.1.8 on 2025-08-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='name',
        ),
    ]
