# Generated by Django 5.2.4 on 2025-08-05 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+905551234567' veya '05551234567' formatında olmalıdır.", regex='^(\\+90|0)?[5][0-9]{9}$')], verbose_name='Telefon Numarası'),
        ),
    ]
