# Generated by Django 5.2.4 on 2025-08-07 00:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='children_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Çocuk Sayısı'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='Çocuğu Var mı?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon numarası geçerli formatta olmalı. Örnek: 05551234567 ya da +905551234567', regex='^(\\+90|0)?5[0-9]{9}$')], verbose_name='Telefon Numarası'),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Çocuk Adı')),
                ('grade', models.CharField(choices=[('3_yas', '3 Yaş'), ('4_yas', '4 Yaş'), ('5_yas', '5 Yaş'), ('1_sinif', '1. Sınıf'), ('2_sinif', '2. Sınıf'), ('3_sinif', '3. Sınıf'), ('4_sinif', '4. Sınıf'), ('5_sinif', '5. Sınıf'), ('6_sinif', '6. Sınıf'), ('7_sinif', '7. Sınıf'), ('8_sinif', '8. Sınıf'), ('9_sinif', '9. Sınıf'), ('10_sinif', '10. Sınıf'), ('11_sinif', '11. Sınıf'), ('12_sinif', '12. Sınıf')], max_length=20, verbose_name='Sınıf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Çocuk',
                'verbose_name_plural': 'Çocuklar',
                'ordering': ['created_at'],
            },
        ),
    ]
