# Generated by Django 4.1.8 on 2025-08-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_code', models.CharField(max_length=50, unique=True, verbose_name='Kampanya Kodu')),
                ('campaign_name', models.CharField(max_length=200, verbose_name='Kampanya Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_code', models.CharField(max_length=6, unique=True, verbose_name='Barkod Kodu')),
                ('barcode_name', models.CharField(max_length=100, verbose_name='Barkod İsmi')),
                ('campaign_code', models.CharField(max_length=50, verbose_name='Kampanya Kodu')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Barkod Görüntüsü')),
                ('is_assigned', models.BooleanField(default=False, verbose_name='Atanmış mı?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kampanya Barkodu',
                'verbose_name_plural': 'Kampanya Barkodları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atanma Tarihi')),
                ('campaign_barcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to='barcodes.campaignbarcode', verbose_name='Kampanya Barkodu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_barcode', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Barkodu',
                'verbose_name_plural': 'Kullanıcı Barkodları',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaignbarcode',
            index=models.Index(fields=['campaign_code', 'is_active'], name='barcodes_ca_campaig_5aa787_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignbarcode',
            index=models.Index(fields=['is_assigned'], name='barcodes_ca_is_assi_888155_idx'),
        ),
    ]
