# Generated by Django 4.1.8 on 2025-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Orijinal Fiyat')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İndirimli Fiyat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunity_products/', verbose_name='Ürün Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Fırsat Ürünü',
                'verbose_name_plural': 'Fırsat Ürünleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
